swagger: "2.0"
info:
  title: Thoth user API
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
paths:
  /liveness:
    get:
      tags: [Service]
      operationId: thoth_api_pkgdeps.api_v1.api_liveness
      summary: Liveness probe for OpenShift.
      responses:
        200:
          description: The Thoth user API service is alive.
  /readiness:
    get:
      tags: [Service]
      operationId: thoth_api_pkgdeps.api_v1.api_readiness
      summary: Readiness probe for OpenShift.
      responses:
        200:
          description: The Thoth user API service is ready.
  /extract-buildlog:
    post:
      operationId: thoth_api_pkgdeps.api_v1.api_extract_buildlog
      summary: Extract Docker build log and show installed packages.
      parameters:
        - name: build_log_info
          in: body
          required: true
          description: A a full build log.
          schema:
            $ref: "#/definitions/BuildLog"
      responses:
        200:
          description: Successful response.
        400:
          description: On invalid request.
  /extract-image:
    post:
      operationId: thoth_api_pkgdeps.api_v1.api_extract_image
      summary: Extract packages installed in a docker image.
      parameters:
        - name: image
          in: query
          required: true
          description: Name of image - can also specify remote registry to pull image from.
          type: string
      responses:
        200:
          description: Successful response.
        400:
          description: On invalid request.

  /analyze:
    post:
      operationId: thoth_api_pkgdeps.api_v1.api_analyze
      summary: Analyze the given image asynchronously.
      parameters:
        - name: image
          in: query
          required: true
          description: Name of image - can also specify remote registry to pull image from.
          type: string
        - name: analyzer
          in: query
          required: true
          description: Name of analyzer (OpenShift build) to be triggered
          type: string
          items:
            type: string
          enum:
            - 'thoth-dependency-extract'
        - name: debug
          in: query
          required: false
          description: Run the given analyzer in a verbose mode so developers can debug analyzer (requires access to the OpenShift console).
          type: boolean
          default: false
        - name: timeout
          in: query
          required: false
          description: Give a timeout to commands run inside the analyzer container.
          type: integer
      responses:
        202:
          description: Successful response.
        400:
          description: On invalid request.

definitions:
  BuildLog:
    type: object
    required:
      - 'buildlog'
    additionalProperties: false
    properties:
      buildlog:
        type: string
        description: A full build log that was output during image build.
        example: >
          Collecting tensorflow
            Downloading tensorflow-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (41.2MB)
          Successfully installed tensorflow-1.4.1
