swagger: "2.0"
info:
  title: API Thoth pkgdeps
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
paths:
  /extract-build-log:
    post:
      operationId: thoth_api_pkgdeps.api_v1.api_extract_build_log
      summary: Extract Docker build log and show installed packages.
      parameters:
        - name: build_log_info
          in: body
          required: true
          description: A a full build log.
          schema:
            $ref: "#/definitions/BuildLog"
      responses:
        200:
          description: Successful response.
        400:
          description: On invalid request.

definitions:
  BuildLog:
    type: object
    required:
      - 'buildlog'
    additionalProperties: false
    properties:
      buildlog:
        type: string
        description: A full build log that was output during image build.
        example: >
          Collecting tensorflow
            Downloading tensorflow-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (41.2MB)
          Successfully installed tensorflow-1.4.1
