apiVersion: v1
kind: Template
labels:
  template: thoth-api-pkgdeps
metadata:
  name: thoth-api-pkgdeps
  annotations:
    description: thoth-api-pkgdeps

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: secret
  data:
    app-secret-key: dmFsdWUtMg0KDQo=
    openshift-api-token: 'RVVsWldPQkNjU3RWSGd0VEhHWGc5dzJ4aHVwRkZ3eGdPWkhlN3lhbjFBTQ=='

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: thoth-api-pkgdeps
    name: thoth-api-pkgdeps
  spec:
    replicas: 1
    selector:
      service: thoth-api-pkgdeps
    template:
      metadata:
        labels:
          service: thoth-api-pkgdeps
      spec:
        containers:
        - env:
          - name: APP_SERVICE_PORT
            value: "34000"
          - name: OPENSHIFT_API_URL
            value: ${OPENSHIFT_API_URL}
          - name: APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: app-secret-key
          - name: OPENSHIFT_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret
                key: openshift-api-token
          image: fridex/thoth-api-pkgdeps
          name: thoth-api-pkgdeps
          ports:
            - containerPort: 34000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: thoth-api-pkgdeps
    name: thoth-api-pkgdeps
  spec:
    ports:
    - name: "34000"
      port: 34000
      protocol: TCP
      targetPort: 34000
    selector:
      service: thoth-api-pkgdeps

- apiVersion: v1
  kind: Route
  metadata:
    name: thoth-api-pkgdeps-4
  spec:
    host: ${THOTH_API_PKGDEPS_HOSTNAME}
    to:
      kind: Service
      name: thoth-api-pkgdeps

parameters:
- description: A hostname where the Thoth API should be exposed (will be auto-generated if empty)
  displayName: Thoth API pkgdeps hostname
  required: false
  name: THOTH_API_PKGDEPS_HOSTNAME

- description: OpenShift API URL in base format (without path).
  displayName: OpenShift base API URL
  required: true
  name: OPENSHIFT_API_URL
  value: 'https://openshift.default.svc.cluster.local'
